---

- name: General | Install Application packages
  apt: "name=curl state=present"

- name: WP-CLI | Download WP-CLI
  shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

- name: WP-CLI | Make WP-CLI executable
  file:
    path: wp-cli.phar
    mode: u=rwx,g=rx,o=rx

- name: WP-CLI | Move WP-CLI to /usr/local/bin/wp
  command: mv wp-cli.phar /usr/local/bin/wp
